# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/

language: node_js
env: TRAVIS_CI=true
# whitelist
branches:
  only:
    - master
node_js:
  - "4"
  - "iojs"
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
